const PREFIX = '@CARACTERS'

export const GET_ALL_CARACTERS = `${PREFIX}/GET_ALL_CARACTERS`;
export const GET_ALL_CARACTERS_SUCCESS = `${PREFIX}/GET_ALL_CARACTERS_SUCCESS`;
export const GET_ALL_CARACTERS_ERROR = `${PREFIX}/GET_ALL_CARACTERS_ERROR`;

export const GET_CARACTER_BY_ID = `${PREFIX}/GET_CARACTER_BY_ID`;
export const GET_CARACTER_BY_ID_SUCCESS = `${PREFIX}/GET_CARACTER_BY_ID_SUCCESS`;
export const GET_CARACTER_BY_ID_ERROR = `${PREFIX}/GET_CARACTER_BY_ID_ERROR`;
